config/routes.rb
EasyDepot::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
  root :to => 'store#index' , :as => 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshop Online</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Bookshop Onlinea">
  <meta name="author" content="Fernando Javier Muñoz">
  <meta name="author" content="Juan Francisco Pose">

  <!-- Le fav and touch icons -->
  <link rel="shortcut icon" href="/assets/app-icon-128.png" >
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/app-icon-128.png" >
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/app-icon-128.png" >
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/app-icon-128.png" >
  <link rel="apple-touch-icon-precomposed" href="/assets/app-icon-48.png" >

</head>
<body id="store">
  <div id="banner">
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>

    <%= image_tag("brand.png" ) %>
    <%= @page_title || t('.title')  %>
  </div>

  <div id="columns">
    <div id="side">

       <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>

      <%= link_to t('.home'),   store_path   %>    <br />

      <a href="/422.html"> <%= t('.questions') %> </a><br />
      <a href="/500.html"><%= t('.news') %> </a><br />
      <a href="#"> <%= t('.contact') %> </a><br />

      <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders',orders_path%><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users',users_path%><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete %>
      <% end %>


    </div>

    <div id="main">
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>